### ISSUE TITLE
Horario segundo semestre

### ISSUE THREAD

**Issue by nicotron** [disenoudd/The-Nature-of-Code#10]
Hola a todos.  

Quisiera que nos dieran los tiempos que tienen disponibles este semestre para quedar con un horario de trabajo.  
En mi caso tengo libre los miércoles y jueves en la mañana.

**Comment by sergiomajluf** [comment]
Hola!
yo los jueves en la mañana también me puedo bloquear una hora

saludos
K

**Comment by nicotron** [comment]
Los horarios que quedaron son los siguientes:

Miércoles 15:00 - 18:00
Jueves 09:00 - 10:00 y 12:00 - 14:00

Estos horarios son para trabajar juntos en el mismo lugar ya sean 2 o todos; de todas maneras con los horarios un poco dispersos podremos sacarle provecho a las herramientas que tiene GitHub para el trabajo en grupo.

**Comment by Paxita** [comment]
Los miércoles salimos a las 11.20 así que podemos partir trabajando desde esa hora (o un poco mas tarde). Vicente tiene que trabajar en el plaza innovación con Pancho pero yo y la palo no. Los jueves tenemos toda la mañana y en la tarde soy ayudante de programación con Nico Zakrzewicz así que se me complica para los jueves.

**Comment by nicotron** [comment]
¿Miércoles desde las 13:00?
