### ISSUE TITLE
Bouncing ball = pelota saltarina v/s pelota que rebota

### ISSUE THREAD

**Issue by palosastre** [disenoudd/The-Nature-of-Code#15]
Estaba terminando de traducir el capítulo 1.1, y me di cuenta de que ya había una parte traducida en el código. Me surgió la duda de si la bouncing ball la nombraremos como pelota saltarina (así estaba en la parte ya traducida del código) ó pelota que rebota.

**Comment by sergiomajluf** [comment]
A mi me gusta saltarían, porque es más juegueton :) pero también porque es
una sola palabra. Mismo criterio que en la Walker Class, que le llamamos
caminante y no "que camina"

K

**Comment by nicotron** [comment]
Entonces queda como **pelota saltarina**
