### ISSUE TITLE
Location = ubicación v/s localización

### ISSUE THREAD

**Issue by palosastre** [disenoudd/The-Nature-of-Code#16]
Tenía entendido que íbamos a usar "localización" como la traducción de "location", pero en algunas partes del código en el capítulo 1.1, está escrito como "ubicación". ¿Cuál usaremos finalmente?

**Comment by sergiomajluf** [comment]
Propongo ubicación, porque en contextos de web por ejemplo, localización de
refiere a la definición del idioma de una web según su ubicación geográfica.

**Comment by nicotron** [comment]
Entonces nos quedamos con **ubicación** y `ubicacion` como variable.
