### ISSUE TITLE
Motion 101

### ISSUE THREAD

**Issue by nicotron** [disenoudd/The-Nature-of-Code#19]
En el capítulo 1.7 se describe "lo más básico para escribir movimiento", y lo hace con el slang **Motion 101** usando _101_ como lo esencial o lo básico.  El problema es que luego comenta el ejercicio **Motion 101** entonces la duda es si usar "esencial" para "101".  
Quedaría así: Motion 101 (lo esencial)  

¿Comentarios al respecto?

**Comment by palosastre** [comment]
En el capítulo 1.8 hay ejercicios y ejemplos como por ejemplo:
"Example 1.9: Motion 101 (velocity and random acceleration)"
Entonces si usamos "Motion 101 (lo esencial)", en el ejemplo traducido sería "Ejemplo 1.9: Motion 101 (lo esencial) (velocidad y aceleración aleatoria)"... 

Creo se se ve raro que esté con paréntesis. Además de que "motion" deberíamos traducirlo también o no? A "movimiento" por ejemplo. 

Quizás puede ser "Lo Esencial del Movimiento" ?

**Comment by nicotron** [comment]
En realidad quedaría como Movimiento 101
