### ISSUE TITLE
Walker es a Caminante, Mover es a?

### ISSUE THREAD

**Issue by nicotron** [disenoudd/The-Nature-of-Code#40]
En el wiki tenemos decidido Walker por Caminante, pero Mover está sin decisión, en e06c457213063bfa9cf041b41132c4150a6fdf20 este commit aparece por primera vez, pero Mover se cambió a Caminante.  
Mover según GoogleTranslate es "agente de mudanza" o sea el "Corredor" de propiedades.
Propongo Corredor como reemplazo a clase Mover

**Comment by sergiomajluf** [comment]
Como lo hablamos el otro día cambié todos los "Movedor(es)" que yo había escrito, por el Caminante. Creo que para este efecto, Mover y Walker son lo mismo. En ambos casos se refiere a la clase de un objeto que se desplaza por la pantalla.

Propongo que los dejemos todos en Caminante no más. Qué te parece?

**Comment by nicotron** [comment]
ok, Caminante para Walker y Mover, actualicé la wiki
